# Generated by Django 4.2.7 on 2023-11-25 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="item",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="summary",
            name="item",
        ),
        migrations.RemoveField(
            model_name="summary",
            name="quantity",
        ),
        migrations.AlterField(
            model_name="cart",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="cart", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.IntegerField(default=1)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="cart_items", to="app.cart"
                    ),
                ),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="app.item")),
            ],
        ),
    ]
